### ISSUE TITLE
Parsing error with scss files

### ISSUE THREAD

**Issue by zallek** [skovhus/SublimeLinter-contrib-sass-lint#4] opened 2015-10-20 12:47 UTC
Since a few days, `SublimeLinter-contrib-sass-lint` bugs on scss files. 

> Please check validity of the block strating from #1.

Example of file (all scss files)

```
SuggestStringSelect {
  display: none;
}
```
# What I tried
1. Removing `SublimeLinter-contrib-sass-lint` -> no more error which prove that this plugin create the error.
2. transforming my file to a sass syntax (by removing braces, etc) -> no more parsing error. Which would mean that it tries to parse scss files as sass files.
# Notes

When I run `sass-lint` in my terminal with the same project, sources and `.sass-lin/yml` it works great. So the issue seems to come from the sublime plugin.

**Comment by rschamp** [comment] 2015-10-22 13:41
I'm experiencing this too. It used to work. I assume a recent update broke this?

**Comment by rschamp** [comment] 2015-10-22 14:19
Just to confirm, release 1.0.1 does not display this behavior.  To get the old version, remove SublimeLinter-contrib-sass-lint via Package Control, then download 1.0.1 from https://github.com/skovhus/SublimeLinter-contrib-sass-lint/releases, unzip and rename the folder `SublimeLinter-contrib-sass-lint` and put it into `~/Library/Application Support/Sublime Text 3/Packages`.

**Comment by donabrams** [comment] 2015-11-09 19:17
This error is caused by the tmp file being renamed to .sass instead of staying .scss which in turn is read as the format by sass-lint (via `'format': 'scss', //path.extname(file).replace('.', ''),` which is passed to groot and fails.

For the moment I just monkey-patched sass-lint/index.js line 94 to `'format': 'scss', //path.extname(file).replace('.', ''),` which is a terrible idea. I can't find the code in SublimeLinter-contrib-sass-lint or SublimeLinter3 that is doing the tmp file copying. Looking into more now.

**Comment by donabrams** [comment] 2015-11-09 20:09
OK, better workaround (but still terrible). In sublimeLinter settings add the following

```
"syntax_map": {
    "sass": "scss",
    ...
}
```

**Comment by donabrams** [comment] 2015-11-09 20:37
After looking into this deeper, it's pretty annoying that sublimelinter doesn't do either of these two things:
1. Preserve the filename when moving to tmp files
2. Allow you to programmatically determine the extname (which it calls suffix for some reason).

Instead it has this silly map convention from view=>syntax=>suffix. Oi.

sass-lint also doesn't have an option to pass the syntax it's checking for (scss or sass) which is also silly.

Since this library is glue code between these two interfaces I'd have to say there's nothing it can do. I think the best bets to get this working are:
1. Add a --syntax option to the sass-lint CLI and modify this lib to use it
2. Directly use lint.lintText as gulp-sass does instead of the CLI tool (https://github.com/sasstools/gulp-sass-lint/blob/master/index.js#L32). This seems way harder.

**Comment by skovhus** [comment] 2015-11-26 22:51
@donabrams @rschamp @zallek I tried reproducing this issue, but cannot using the newest version of `SublimeLinter-contrib-sass-lint`, Sublime 3 and `sass-lint@1.3.3`. 

The error explained will be thrown if the syntax is set to `sass` but it really is `scss` code. Please check that the syntax of the file you are editing is set correctly in the lower right corner of sublime. If not, maybe you need to install the `scss/sass` Sublime package. Please let me know if this is the problem for you guys... Then we can figure out a workaround for this.

@donabrams thanks for working on this, but I cannot see Sublime Linter doing anything wrong here. If the syntax is set correctly for the file that you are editing, they are preserving the file name.

**Comment by Bnaya** [comment] 2015-12-02 14:43
I also have this issue
its linting .scss files as they sass files.

My original file is app.scss and in the sublime log i see this:

```
SublimeLinter: chdir not set or invalid, using /Users/bnaya/dev/blallala/mobile-app/src/scss 
SublimeLinter: sass: app.scss ['/Users/bnaya/dev/blallala/mobile-app/node_modules/.bin/sass-lint', '--verbose', '--no-exit'] 
SublimeLinter: sass output:
/Users/bnaya/dev/blallala/mobile-app/node_modules/sass-lint/lib/groot.js:21
    throw new Error('Parsing error' + fileInfo + ': ' + e.message);
          ^
Error: Parsing error at /var/folders/4v/6vck4yf13952lzwwlv1z2j2m0000gn/T/SublimeLinter3-bnaya/app.sass: Please check validity of the block starting from line #1
    at module.exports (/Users/bnaya/dev/blallala/mobile-app/node_modules/sass-lint/lib/groot.js:21:11)
    at Function.sassLint.lintText (/Users/bnaya/dev/photomania/mobile-app/node_modules/sass-lint/index.js:36:13)
    at /Users/bnaya/dev/blallala/mobile-app/node_modules/sass-lint/index.js:91:21
    at Array.forEach (native)
    at Function.sassLint.lintFiles (/Users/bnaya/dev/blallala/mobile-app/node_modules/sass-lint/index.js:90:9)
    at detectPattern (/Users/bnaya/dev/blallala/mobile-app/node_modules/sass-lint/bin/sass-lint.js:15:18)
    at /Users/bnaya/dev/blallala/mobile-app/node_modules/sass-lint/bin/sass-lint.js:81:5
    at Array.forEach (native)
    at Object.<anonymous> (/Users/bnaya/dev/blallala/mobile-app/node_modules/sass-lint/bin/sass-lint.js:80:16)
    at Module._compile (module.js:460:26) 
```

**Comment by skovhus** [comment] 2015-12-02 15:48
@Bnaya thanks. Which sass-lint version? `sass-lint --version`

**Comment by Bnaya** [comment] 2015-12-02 15:52
1.3.3,
my gulp sass lint that uses sass-lint works ok
I think its should be something with the linter plugin

**Comment by skovhus** [comment] 2015-12-02 16:17
Can you paste a snippet of your `app.sass` file?

**Comment by Bnaya** [comment] 2015-12-02 16:32
scss file:

``` scss
body {
    background-color: #fff;
    color: green;
}

html {
    color: green;
}
```

**Comment by skovhus** [comment] 2015-12-02 16:50
And the file is called `app.sass` not `app.scss`?

**Comment by Bnaya** [comment] 2015-12-02 16:51
the file called app.scss but the plugin renaming it to app.sass

**Comment by skovhus** [comment] 2015-12-02 16:51
What is the syntax in Sublime, see bottom right corner?

**Comment by Bnaya** [comment] 2015-12-02 16:54
sass

**Comment by skovhus** [comment] 2015-12-02 17:00
That is the problem. The file is scss. Try changing the syntax to scss (maybe you need to install that syntax as a package).

**Comment by Bnaya** [comment] 2015-12-02 17:03
@skovhus i've installed the package and problem solved :)
Thanks!
The package:
![screen shot 2015-12-02 at 7 02 24 pm](https://cloud.githubusercontent.com/assets/1304862/11537778/5105a778-9927-11e5-92fb-71d7718de196.png)
I would suggest to add a note about it in the plugin docs

**Comment by rschamp** [comment] 2015-12-02 17:04
If the problem is the syntax, not the plugin, then why does 1.0.1 work for .scss files? My whole team is using 1.0.1 due to this.

**Comment by skovhus** [comment] 2015-12-02 17:08
@rschamp 1.0.2 added support for both scss and sass based on the syntax you
have selected. Your syntax is clearly misconfigured. : ) But I will
see if we should revert that change, assuming that a lot of people
misconfigure their syntax with SCSS/sass.

**Comment by Bnaya** [comment] 2015-12-02 17:13
i haven't configured it manually, at least i don't remember i did
Maybe plugin that i've installed at the past added sass support, and caused scss files to be marked as sass.
And the error you get is very cryptic that its hard to find that problem.
It might be a problem in the SublimeLinter infrastructure level

**Comment by skovhus** [comment] 2015-12-02 22:58
@rschamp can you try changing to SCSS syntax, and see if it solves your problem?

**Comment by karlhorky** [comment] 2016-01-04 22:41
I had this issue and switching to SCSS syntax with the TextMate SCSS Official Bundle worked. Thanks @skovhus!

**Closed as completed** 2016-02-12 21:55 UTC
